// Generated by Arabiki64 V1.2
// By Buu342


// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_fence[] = {
    {-7, -7, 0, 0, 0, 0, -73, -73, -73, 255}, /* 0 */
    {-7, -7, 125, 0, 0, 0, -85, -85, 41, 255}, /* 1 */
    {-7, 7, 125, 0, 0, 0, -85, 85, 41, 255}, /* 2 */
    {-7, 7, 0, 0, 0, 0, -73, 73, -73, 255}, /* 3 */
    {7, 7, 125, 0, 0, 0, 74, 92, 47, 255}, /* 4 */
    {7, 7, 0, 0, 0, 0, 60, 83, -76, 255}, /* 5 */
    {7, -7, 125, 0, 0, 0, 74, -92, 47, 255}, /* 6 */
    {7, -7, 0, 0, 0, 0, 60, -83, -76, 255}, /* 7 */
    {8, -2, 0, 0, 0, 0, 37, -51, -110, 255}, /* 8 */
    {8, -2, 125, 0, 0, 0, 37, -51, 110, 255}, /* 9 */
    {3, -3, 131, 0, 0, 0, 80, -80, 57, 255}, /* 10 */
    {-3, -3, 131, 0, 0, 0, -80, -80, 57, 255}, /* 11 */
    {3, 3, 131, 0, 0, 0, 80, 80, 57, 255}, /* 12 */
    {3, 3, 133, 0, 0, 0, 85, 85, -43, 255}, /* 13 */
    {3, -3, 133, 0, 0, 0, 85, -85, -43, 255}, /* 14 */
    {-3, 3, 131, 0, 0, 0, -80, 80, 57, 255}, /* 15 */
    {7, 7, 141, 0, 0, 0, 90, 86, 25, 255}, /* 16 */
    {7, -7, 141, 0, 0, 0, 86, -88, 31, 255}, /* 17 */
    {-3, -3, 133, 0, 0, 0, -85, -85, -43, 255}, /* 18 */
    {-3, 3, 133, 0, 0, 0, -85, 85, -43, 255}, /* 19 */
    {8, 2, 125, 0, 0, 0, 37, 51, 110, 255}, /* 20 */
    {502, -2, 125, 0, 0, 0, 73, -73, 73, 255}, /* 21 */
    {502, 2, 125, 0, 0, 0, 73, 73, 73, 255}, /* 22 */
    {-7, -7, 141, 0, 0, 0, -86, -88, 31, 255}, /* 23 */
    {-7, 7, 141, 0, 0, 0, -90, 86, 24, 255}, /* 24 */
    {0, 3, 145, 0, 0, 0, -2, 22, 125, 255}, /* 25 */
    {8, 2, 0, 0, 0, 0, 37, 51, -110, 255}, /* 26 */
    {502, 2, 0, 0, 0, 0, 73, 73, -73, 255}, /* 27 */
    {502, -2, 0, 0, 0, 0, 73, -73, -73, 255}, /* 28 */
};

static Gfx gfx_fence[] = {
    gsSPVertex(vtx_fence+0, 29, 0),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_PRIMLITE, G_CC_PRIMLITE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPSetPrimColor(0, 0, 30, 30, 30, 255),
    gsDPPipeSync(),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(6, 7, 8, 0, 6, 8, 9, 0),
    gsSP2Triangles(7, 6, 1, 0, 7, 1, 0, 0),
    gsSP2Triangles(3, 5, 7, 0, 3, 7, 0, 0),
    gsSP2Triangles(1, 6, 10, 0, 1, 10, 11, 0),
    gsSP2Triangles(10, 12, 13, 0, 10, 13, 14, 0),
    gsSP2Triangles(4, 2, 15, 0, 4, 15, 12, 0),
    gsSP2Triangles(6, 4, 12, 0, 6, 12, 10, 0),
    gsSP2Triangles(2, 1, 11, 0, 2, 11, 15, 0),
    gsSP2Triangles(14, 13, 16, 0, 14, 16, 17, 0),
    gsSP2Triangles(15, 11, 18, 0, 15, 18, 19, 0),
    gsSP2Triangles(11, 10, 14, 0, 11, 14, 18, 0),
    gsSP2Triangles(12, 15, 19, 0, 12, 19, 13, 0),
    gsSP2Triangles(20, 9, 21, 0, 20, 21, 22, 0),
    gsSP2Triangles(19, 18, 23, 0, 19, 23, 24, 0),
    gsSP2Triangles(18, 14, 17, 0, 18, 17, 23, 0),
    gsSP2Triangles(13, 19, 24, 0, 13, 24, 16, 0),
    gsSP2Triangles(16, 24, 25, 0, 24, 23, 25, 0),
    gsSP2Triangles(23, 17, 25, 0, 17, 16, 25, 0),
    gsSP2Triangles(7, 5, 26, 0, 7, 26, 8, 0),
    gsSP2Triangles(4, 6, 9, 0, 4, 9, 20, 0),
    gsSP2Triangles(5, 4, 20, 0, 5, 20, 26, 0),
    gsSP2Triangles(27, 22, 21, 0, 27, 21, 28, 0),
    gsSP2Triangles(26, 20, 22, 0, 26, 22, 27, 0),
    gsSP2Triangles(9, 8, 28, 0, 9, 28, 21, 0),
    gsSP2Triangles(8, 26, 27, 0, 8, 27, 28, 0),
    gsSPEndDisplayList(),
};

