// Generated by Arabiki64 V1.3
// By Buu342


// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_gravestone_cross[] = {
    {-16, -20, 94, 0, 0, 0, -115, -38, -38, 255}, /* 0 */
    {-16, -20, 134, 0, 0, 0, -115, -38, 38, 255}, /* 1 */
    {-16, 20, 134, 0, 0, 0, -115, 38, 38, 255}, /* 2 */
    {-16, 20, 94, 0, 0, 0, -115, 38, -38, 255}, /* 3 */
    {16, 20, 134, 0, 0, 0, 115, 38, 38, 255}, /* 4 */
    {16, 20, 94, 0, 0, 0, 115, 38, -38, 255}, /* 5 */
    {16, 60, 94, 0, 0, 0, 73, 73, -73, 255}, /* 6 */
    {16, 60, 134, 0, 0, 0, 73, 73, 73, 255}, /* 7 */
    {16, -20, 134, 0, 0, 0, 115, -38, 38, 255}, /* 8 */
    {16, -20, 94, 0, 0, 0, 115, -38, -38, 255}, /* 9 */
    {-16, -59, 94, 0, 0, 0, -73, -73, -73, 255}, /* 10 */
    {-16, -59, 134, 0, 0, 0, -73, -73, 73, 255}, /* 11 */
    {-16, -20, 4, 0, 0, 0, -73, -73, -73, 255}, /* 12 */
    {16, -20, 4, 0, 0, 0, 73, -73, -73, 255}, /* 13 */
    {-16, 20, 173, 0, 0, 0, -73, 73, 73, 255}, /* 14 */
    {16, 20, 173, 0, 0, 0, 73, 73, 73, 255}, /* 15 */
    {-16, -20, 173, 0, 0, 0, -73, -73, 73, 255}, /* 16 */
    {16, -20, 173, 0, 0, 0, 73, -73, 73, 255}, /* 17 */
    {-16, 60, 94, 0, 0, 0, -73, 73, -73, 255}, /* 18 */
    {-16, 60, 134, 0, 0, 0, -73, 73, 73, 255}, /* 19 */
    {16, -59, 94, 0, 0, 0, 73, -73, -73, 255}, /* 20 */
    {16, -59, 134, 0, 0, 0, 73, -73, 73, 255}, /* 21 */
    {-16, 20, 4, 0, 0, 0, -73, 73, -73, 255}, /* 22 */
    {16, 20, 4, 0, 0, 0, 73, 73, -73, 255}, /* 23 */
};

static Gfx gfx_gravestone_cross[] = {
    gsSPVertex(vtx_gravestone_cross+0, 24, 0),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_PRIMLITE, G_CC_PRIMLITE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPSetPrimColor(0, 0, 80, 80, 80, 255),
    gsDPPipeSync(),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSP2Triangles(5, 4, 8, 0, 5, 8, 9, 0),
    gsSP2Triangles(1, 0, 10, 0, 1, 10, 11, 0),
    gsSP2Triangles(9, 0, 12, 0, 9, 12, 13, 0),
    gsSP2Triangles(4, 2, 14, 0, 4, 14, 15, 0),
    gsSP2Triangles(15, 14, 16, 0, 15, 16, 17, 0),
    gsSP2Triangles(8, 4, 15, 0, 8, 15, 17, 0),
    gsSP2Triangles(2, 1, 16, 0, 2, 16, 14, 0),
    gsSP2Triangles(1, 8, 17, 0, 1, 17, 16, 0),
    gsSP2Triangles(18, 19, 7, 0, 18, 7, 6, 0),
    gsSP2Triangles(5, 3, 18, 0, 5, 18, 6, 0),
    gsSP2Triangles(2, 4, 7, 0, 2, 7, 19, 0),
    gsSP2Triangles(3, 2, 19, 0, 3, 19, 18, 0),
    gsSP2Triangles(20, 21, 11, 0, 20, 11, 10, 0),
    gsSP2Triangles(0, 9, 20, 0, 0, 20, 10, 0),
    gsSP2Triangles(8, 1, 11, 0, 8, 11, 21, 0),
    gsSP2Triangles(9, 8, 21, 0, 9, 21, 20, 0),
    gsSP2Triangles(22, 23, 13, 0, 22, 13, 12, 0),
    gsSP2Triangles(3, 5, 23, 0, 3, 23, 22, 0),
    gsSP2Triangles(0, 3, 22, 0, 0, 22, 12, 0),
    gsSP2Triangles(5, 9, 13, 0, 5, 13, 23, 0),
    gsSPEndDisplayList(),
};

