// Generated by Arabiki64 V1.3
// By Buu342


// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_gravestone_flat_2[] = {
    {-25, 30, 20, 0, 0, 0, 92, -73, 48, 255}, /* 0 */
    {-22, 30, 29, 0, 0, 0, 48, -73, -92, 255}, /* 1 */
    {-22, -34, 29, 0, 0, 0, 48, 73, -92, 255}, /* 2 */
    {-25, -34, 20, 0, 0, 0, 92, 73, 48, 255}, /* 3 */
    {-12, -34, 26, 0, 0, 0, -92, 73, -48, 255}, /* 4 */
    {-15, -34, 17, 0, 0, 0, -48, 73, 92, 255}, /* 5 */
    {-12, 30, 26, 0, 0, 0, -92, -73, -48, 255}, /* 6 */
    {-15, 30, 17, 0, 0, 0, -48, -73, 92, 255}, /* 7 */
    {0, 22, 11, 0, 0, 0, 92, -73, 48, 255}, /* 8 */
    {3, 22, 20, 0, 0, 0, 48, -73, -92, 255}, /* 9 */
    {3, -26, 20, 0, 0, 0, 48, 73, -92, 255}, /* 10 */
    {0, -26, 11, 0, 0, 0, 92, 73, 48, 255}, /* 11 */
    {12, -26, 17, 0, 0, 0, -92, 73, -48, 255}, /* 12 */
    {9, -26, 8, 0, 0, 0, -48, 73, 92, 255}, /* 13 */
    {12, 22, 17, 0, 0, 0, -92, -73, -48, 255}, /* 14 */
    {9, 22, 8, 0, 0, 0, -48, -73, 92, 255}, /* 15 */
    {-33, -52, -12, 0, 0, 0, -73, -73, -73, 255}, /* 16 */
    {-33, -52, 29, 0, 0, 0, -60, -71, 86, 255}, /* 17 */
    {-33, 51, 29, 0, 0, 0, -60, 71, 86, 255}, /* 18 */
    {-33, 51, -12, 0, 0, 0, -73, 73, -73, 255}, /* 19 */
    {28, 51, 6, 0, 0, 0, 84, 76, 58, 255}, /* 20 */
    {28, 51, -12, 0, 0, 0, 73, 73, -73, 255}, /* 21 */
    {28, -52, 6, 0, 0, 0, 84, -76, 58, 255}, /* 22 */
    {28, -52, -12, 0, 0, 0, 73, -73, -73, 255}, /* 23 */
};

static Gfx gfx_gravestone_flat_2[] = {
    gsSPVertex(vtx_gravestone_flat_2+0, 24, 0),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_PRIMLITE, G_CC_PRIMLITE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPSetPrimColor(0, 0, 20, 20, 20, 255),
    gsDPPipeSync(),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(7, 6, 1, 0, 7, 1, 0, 0),
    gsSP2Triangles(3, 5, 7, 0, 3, 7, 0, 0),
    gsSP2Triangles(4, 2, 1, 0, 4, 1, 6, 0),
    gsSP2Triangles(8, 9, 10, 0, 8, 10, 11, 0),
    gsSP2Triangles(11, 10, 12, 0, 11, 12, 13, 0),
    gsSP2Triangles(13, 12, 14, 0, 13, 14, 15, 0),
    gsSP2Triangles(15, 14, 9, 0, 15, 9, 8, 0),
    gsSP2Triangles(11, 13, 15, 0, 11, 15, 8, 0),
    gsSP2Triangles(12, 10, 9, 0, 12, 9, 14, 0),
    gsDPSetPrimColor(0, 0, 80, 80, 80, 255),
    gsSP2Triangles(16, 17, 18, 0, 16, 18, 19, 0),
    gsSP2Triangles(19, 18, 20, 0, 19, 20, 21, 0),
    gsSP2Triangles(21, 20, 22, 0, 21, 22, 23, 0),
    gsSP2Triangles(23, 22, 17, 0, 23, 17, 16, 0),
    gsSP2Triangles(19, 21, 23, 0, 19, 23, 16, 0),
    gsSP2Triangles(20, 18, 17, 0, 20, 17, 22, 0),
    gsSPEndDisplayList(),
};

