// Generated by Arabiki64 V1.3
// By Buu342


// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_gravestone_cross[] = {
    {1, -1, 4, 0, 0, 0, -115, 38, 38, 255}, /* 0 */
    {1, -1, 6, 0, 0, 0, -114, 0, 57, 255}, /* 1 */
    {1, 1, 6, 0, 0, 0, -114, 0, 57, 255}, /* 2 */
    {1, 1, 4, 0, 0, 0, -115, -38, 38, 255}, /* 3 */
    {-1, 1, 4, 0, 0, 0, 115, -38, 38, 255}, /* 4 */
    {1, 3, 4, 0, 0, 0, -73, -73, 73, 255}, /* 5 */
    {-1, 3, 4, 0, 0, 0, 73, -73, 73, 255}, /* 6 */
    {-1, 1, 6, 0, 0, 0, 114, 0, 57, 255}, /* 7 */
    {-1, -1, 6, 0, 0, 0, 114, 0, 57, 255}, /* 8 */
    {-1, -1, 4, 0, 0, 0, 115, 38, 38, 255}, /* 9 */
    {1, -3, 6, 0, 0, 0, -73, 73, -73, 255}, /* 10 */
    {-1, -3, 6, 0, 0, 0, 73, 73, -73, 255}, /* 11 */
    {1, -1, 0, 0, 0, 0, -73, 73, 73, 255}, /* 12 */
    {-1, -1, 0, 0, 0, 0, 73, 73, 73, 255}, /* 13 */
    {1, -1, 6, 0, 0, 0, 0, 0, 127, 255}, /* 14 */
    {1, 1, 6, 0, 0, 0, 0, 0, 127, 255}, /* 15 */
    {-1, -1, 6, 0, 0, 0, 0, 0, 127, 255}, /* 16 */
    {-1, 1, 6, 0, 0, 0, 0, 0, 127, 255}, /* 17 */
    {-1, 1, 6, 0, 0, 0, 52, -52, 104, 255}, /* 18 */
    {-1, -1, 6, 0, 0, 0, 52, 52, 104, 255}, /* 19 */
    {1, -1, 6, 0, 0, 0, -52, 52, 104, 255}, /* 20 */
    {-1, -1, 8, 0, 0, 0, 73, 73, -73, 255}, /* 21 */
    {1, -1, 8, 0, 0, 0, -73, 73, -73, 255}, /* 22 */
    {1, 1, 6, 0, 0, 0, -52, -52, 104, 255}, /* 23 */
    {-1, 1, 8, 0, 0, 0, 73, -73, -73, 255}, /* 24 */
    {1, 1, 8, 0, 0, 0, -73, -73, -73, 255}, /* 25 */
    {-1, -3, 4, 0, 0, 0, 73, 73, 73, 255}, /* 26 */
    {1, -3, 4, 0, 0, 0, -73, 73, 73, 255}, /* 27 */
    {1, 3, 6, 0, 0, 0, -73, -73, -73, 255}, /* 28 */
    {-1, 3, 6, 0, 0, 0, 73, -73, -73, 255}, /* 29 */
    {1, 1, 0, 0, 0, 0, -73, -73, 73, 255}, /* 30 */
    {-1, 1, 0, 0, 0, 0, 73, -73, 73, 255}, /* 31 */
};

static Gfx gfx_gravestone_cross[] = {
    gsSPVertex(vtx_gravestone_cross+0, 32, 0),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_PRIMLITE, G_CC_PRIMLITE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPSetPrimColor(0, 0, 80, 80, 80, 255),
    gsDPPipeSync(),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 3, 5, 0, 4, 5, 6, 0),
    gsSP2Triangles(4, 7, 8, 0, 4, 8, 9, 0),
    gsSP2Triangles(8, 1, 10, 0, 8, 10, 11, 0),
    gsSP2Triangles(9, 0, 12, 0, 9, 12, 13, 0),
    gsSP2Triangles(2, 1, 14, 0, 2, 14, 15, 0),
    gsSP2Triangles(14, 16, 16, 0, 14, 16, 14, 0),
    gsSP2Triangles(1, 8, 16, 0, 1, 16, 14, 0),
    gsSP2Triangles(7, 2, 15, 0, 7, 15, 17, 0),
    gsSP2Triangles(8, 7, 17, 0, 8, 17, 16, 0),
    gsSP2Triangles(16, 17, 18, 0, 16, 18, 19, 0),
    gsSP2Triangles(17, 15, 15, 0, 17, 15, 17, 0),
    gsSP2Triangles(16, 17, 17, 0, 16, 17, 16, 0),
    gsSP2Triangles(15, 14, 14, 0, 15, 14, 15, 0),
    gsSP2Triangles(20, 19, 21, 0, 20, 21, 22, 0),
    gsSP2Triangles(15, 14, 20, 0, 15, 20, 23, 0),
    gsSP2Triangles(14, 16, 19, 0, 14, 19, 20, 0),
    gsSP2Triangles(17, 15, 23, 0, 17, 23, 18, 0),
    gsSP2Triangles(24, 25, 22, 0, 24, 22, 21, 0),
    gsSP2Triangles(18, 23, 25, 0, 18, 25, 24, 0),
    gsSP2Triangles(19, 18, 24, 0, 19, 24, 21, 0),
    gsSP2Triangles(23, 20, 22, 0, 23, 22, 25, 0),
    gsSP2Triangles(26, 11, 10, 0, 26, 10, 27, 0),
    gsSP2Triangles(9, 8, 11, 0, 9, 11, 26, 0),
    gsSP2Triangles(1, 0, 27, 0, 1, 27, 10, 0),
    gsSP2Triangles(0, 9, 26, 0, 0, 26, 27, 0),
    gsSP2Triangles(5, 28, 29, 0, 5, 29, 6, 0),
    gsSP2Triangles(2, 7, 29, 0, 2, 29, 28, 0),
    gsSP2Triangles(3, 2, 28, 0, 3, 28, 5, 0),
    gsSP2Triangles(7, 4, 6, 0, 7, 6, 29, 0),
    gsSP2Triangles(30, 31, 13, 0, 30, 13, 12, 0),
    gsSP2Triangles(3, 4, 31, 0, 3, 31, 30, 0),
    gsSP2Triangles(0, 3, 30, 0, 0, 30, 12, 0),
    gsSP2Triangles(4, 9, 13, 0, 4, 13, 31, 0),
    gsSPEndDisplayList(),
};

