// Generated by Arabiki64 V1.3
// By Buu342


// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_ground[] = {
    {781, 100, -81, 0, 0, 0, 73, 73, 73, 255}, /* 0 */
    {-100, 100, -81, 0, 0, 0, -73, 73, 73, 255}, /* 1 */
    {-100, -731, -81, 0, 0, 0, -73, -73, 73, 255}, /* 2 */
    {781, -731, -81, 0, 0, 0, 73, -73, 73, 255}, /* 3 */
    {781, -731, -100, 0, 0, 0, 73, -73, -73, 255}, /* 4 */
    {-100, -731, -100, 0, 0, 0, -73, -73, -73, 255}, /* 5 */
    {-100, 100, -100, 0, 0, 0, -73, 73, -73, 255}, /* 6 */
    {781, 100, -100, 0, 0, 0, 73, 73, -73, 255}, /* 7 */
};

static Gfx gfx_ground[] = {
    gsDPSetPrimColor(0, 0, 4, 75, 24, 255),
    gsDPPipeSync(),
    gsSPVertex(vtx_ground+0, 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 3, 2, 0, 4, 2, 5, 0),
    gsSP2Triangles(5, 2, 1, 0, 5, 1, 6, 0),
    gsSP2Triangles(6, 7, 4, 0, 6, 4, 5, 0),
    gsSP2Triangles(7, 0, 3, 0, 7, 3, 4, 0),
    gsSP2Triangles(6, 1, 0, 0, 6, 0, 7, 0),
    gsSPEndDisplayList(),
};

