// Generated by Arabiki64 V1.3
// By Buu342


// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_ground[] = {
    {7810, 1000, -813, 0, 0, 0, 73, 73, 73, 255}, /* 0 */
    {-1000, 1000, -813, 0, 0, 0, -73, 73, 73, 255}, /* 1 */
    {-1000, -7315, -813, 0, 0, 0, -73, -73, 73, 255}, /* 2 */
    {7810, -7315, -813, 0, 0, 0, 73, -73, 73, 255}, /* 3 */
    {7810, -7315, -1000, 0, 0, 0, 73, -73, -73, 255}, /* 4 */
    {-1000, -7315, -1000, 0, 0, 0, -73, -73, -73, 255}, /* 5 */
    {-1000, 1000, -1000, 0, 0, 0, -73, 73, -73, 255}, /* 6 */
    {7810, 1000, -1000, 0, 0, 0, 73, 73, -73, 255}, /* 7 */
};

static Gfx gfx_ground[] = {
    /*
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_PRIMLITE, G_CC_PRIMLITE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    */
    gsDPSetPrimColor(0, 0, 46, 77, 46, 255),
    gsDPPipeSync(),
    gsSPVertex(vtx_ground+0, 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 3, 2, 0, 4, 2, 5, 0),
    gsSP2Triangles(5, 2, 1, 0, 5, 1, 6, 0),
    gsSP2Triangles(6, 7, 4, 0, 6, 4, 5, 0),
    gsSP2Triangles(7, 0, 3, 0, 7, 3, 4, 0),
    gsSP2Triangles(6, 1, 0, 0, 6, 0, 7, 0),
    gsSPEndDisplayList(),
};

