// Generated by Arabiki64 V1.3
// By Buu342


// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_MyModel[] = {
    {-25, -25, -25, 0, 0, 0, -73, -73, -73, 255}, /* 0 */
    {-25, -25, 25, 0, 0, 0, -73, -73, 73, 255}, /* 1 */
    {-25, 25, 25, 0, 0, 0, -73, 73, 73, 255}, /* 2 */
    {-25, 25, -25, 0, 0, 0, -73, 73, -73, 255}, /* 3 */
    {25, 25, 25, 0, 0, 0, 73, 73, 73, 255}, /* 4 */
    {25, 25, -25, 0, 0, 0, 73, 73, -73, 255}, /* 5 */
    {25, -25, 25, 0, 0, 0, 73, -73, 73, 255}, /* 6 */
    {25, -25, -25, 0, 0, 0, 73, -73, -73, 255}, /* 7 */
    {-25, -25, 25, 0, 0, 0, -73, -73, 73, 255}, /* 8 */
    {-25, -25, -25, 0, 0, 0, -73, -73, -73, 255}, /* 9 */
    {-25, 25, -25, 0, 0, 0, -73, 73, -73, 255}, /* 10 */
    {-25, -25, -25, 0, 0, 0, -73, -73, -73, 255}, /* 11 */
    {-25, 25, 25, 0, 0, 0, -73, 73, 73, 255}, /* 12 */
    {-25, -25, 25, 0, 0, 0, -73, -73, 73, 255}, /* 13 */
};

static Gfx gfx_MyModel[] = {
    gsSPVertex(vtx_MyModel+0, 14, 0),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_PRIMLITE, G_CC_PRIMLITE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPSetPrimColor(0, 0, 10, 10, 10, 255),
    gsDPPipeSync(),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsDPSetPrimColor(0, 0, 155, 112, 87, 255),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsDPSetPrimColor(0, 0, 122, 100, 45, 255),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsDPSetPrimColor(0, 0, 100, 200, 80, 255),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsSP1Triangle(0, 2, 3, 0),
    gsSP1Triangle(3, 2, 4, 0),
    gsSP1Triangle(3, 4, 5, 0),
    gsSP1Triangle(5, 4, 6, 0),
    gsSP1Triangle(5, 6, 7, 0),
    gsSP1Triangle(7, 6, 8, 0),
    gsSP1Triangle(7, 8, 9, 0),
    gsSP1Triangle(10, 5, 7, 0),
    gsSP1Triangle(10, 7, 11, 0),
    gsSP1Triangle(4, 12, 13, 0),
    gsSP1Triangle(4, 13, 6, 0),
    gsSP1Triangle(0, 1, 2, 0),
    gsSP1Triangle(0, 2, 3, 0),
    gsSP1Triangle(3, 2, 4, 0),
    gsSP1Triangle(3, 4, 5, 0),
    gsSP1Triangle(5, 4, 6, 0),
    gsSP1Triangle(5, 6, 7, 0),
    gsSP1Triangle(7, 6, 8, 0),
    gsSP1Triangle(7, 8, 9, 0),
    gsSP1Triangle(10, 5, 7, 0),
    gsSP1Triangle(10, 7, 11, 0),
    gsSP1Triangle(4, 12, 13, 0),
    gsSP1Triangle(4, 13, 6, 0),
    gsDPSetPrimColor(0, 0, 200, 80, 120, 255),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsDPSetPrimColor(0, 0, 240, 240, 240, 255),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSP2Triangles(4, 12, 13, 0, 4, 13, 6, 0),
    gsSP2Triangles(7, 6, 8, 0, 7, 8, 9, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(10, 5, 7, 0, 10, 7, 11, 0),
    gsSP2Triangles(5, 4, 6, 0, 5, 6, 7, 0),
    gsSP2Triangles(3, 2, 4, 0, 3, 4, 5, 0),
    gsSPEndDisplayList(),
};

